service: aws-java-devops-test

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  deploymentBucket:
    name: bucket-lambdas-prada
package:
  artifact: build/distributions/add_clients.zip
      
functions:
  currentTime:
    handler: com.serverless.AddClientHandler
    events:
      - http:
          path: ping
method: post